name: python CI

on:
  push:
    branches: [ "main" ]

jobs:

    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: py.test
    deploy: 
        name: deploy 
        needs: [build] 
        runs-on: ubuntu-latest 
        steps: 
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with: 
              service-id: ${{ secrets.SECRET_ID }}
              api-key: ${{ secrets.SECRET_KEY }}
    message: 
        needs: [build]
        if: failure()
        runs-on: ubuntu-latest
        steps: 
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: '#ff00ff' # or a specific color like 'good' or '#ff00ff'
              SLACK_ICON: https://github.com/rtCamp.png?size=48
              SLACK_MESSAGE: 'fallo'
              SLACK_TITLE: Post Title
              SLACK_USERNAME: rtCamp
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}